/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentPosts: Array<HydratedFrontmatter> = [
  {
    "title": "Async Class Creation In JavaScript",
    "slug": "async-class-creation-in-javascript",
    "path": "/2025/june/async-class-creation-in-javascript",
    "date": 1748981098396,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "JavaScript",
      "TypeScript",
      "Tip"
    ],
    "description": "Have you ever wanted to create a class in JavaScript or TypeScript but also have the initialization be async? Here's a quick tip on a pattern that I've used in the past!",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/async-class-creation-in-javascript.png",
    "lastModified": 1748981231000
  },
  {
    "title": "In Review - The Belroy Transit Workpack Pro v2",
    "slug": "belroy-transit-workpack-pro-v2",
    "path": "/2025/may/belroy-transit-workpack-pro-v2",
    "date": 1748517015808,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Product Review",
      "Backpack",
      "Gear",
      "Review"
    ],
    "description": "I semi-recently bought a Belroy Transit Workpack Pro v2 backpack, and after using it for about 9 months now I figured I'd write up some of my thoughts on it!",
    "month": "may",
    "year": 2025,
    "ogImage": "/og-images/belroy-transit-workpack-pro-v2.png",
    "lastModified": 1748517256000
  },
  {
    "title": "Website Redesign v10",
    "slug": "website-redesign-v10",
    "path": "/2025/may/website-redesign-v10",
    "date": 1748209536031,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "Redesign"
    ],
    "description": "I recently launched a rewrite and redesign of this personal website, I figured I'd talk a bit about the changes and new features that I added along the way!",
    "month": "may",
    "year": 2025,
    "ogImage": "/og-images/website-redesign-v10.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lpzvssqktc23",
    "lastModified": 1748209751000
  },
  {
    "title": "Server Side Rendering Compatible CSS Theming",
    "slug": "server-side-rendering-compatible-css-theming",
    "path": "/2025/april/server-side-rendering-compatible-css-theming",
    "date": 1744749638305,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Theming",
      "CSS",
      "Next.js",
      "Waku",
      "React",
      "Tip"
    ],
    "description": "A quick tip to implementing CSS theming that's compatible with Server Side Rendered applications!",
    "month": "april",
    "year": 2025,
    "ogImage": "/og-images/server-side-rendering-compatible-css-theming.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lmuxdbcyzs27",
    "lastModified": 1747568207000
  },
  {
    "title": "Podcasting By Hand",
    "slug": "podcasting-by-hand",
    "path": "/2025/april/podcasting-by-hand",
    "date": 1744629340844,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Podcasting",
      "The Bikeshed Pod"
    ],
    "description": "A brief overview on how we launched The Bikeshed Podcast, including a deep dive in our recording and distribution workflows!",
    "month": "april",
    "year": 2025,
    "ogImage": "/og-images/podcasting-by-hand.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lmrgykvctc2s",
    "lastModified": 1747568207000
  }
]