/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentPosts: Array<HydratedFrontmatter> = [
  {
    "title": "Roundup Notes in Obsidian with Dataview",
    "slug": "roundup-notes-in-obsidian-with-dataview",
    "path": "/2025/june/roundup-notes-in-obsidian-with-dataview",
    "date": 1750115552955,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Obsidian",
      "Tip",
      "Note Taking",
      "Development"
    ],
    "description": "A quick tip for creating roundup or summary notes based on other notes in Obsidian using the Dataview plugin!",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/roundup-notes-in-obsidian-with-dataview.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lrr4ixwydc2d",
    "location": "",
    "lastModified": 1750115960000
  },
  {
    "title": "Quick Tip - Theme Aware Images",
    "slug": "quick-tip-theme-aware-images",
    "path": "/2025/june/quick-tip-theme-aware-images",
    "date": 1750114295541,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Tip",
      "Web Development",
      "Development"
    ],
    "description": "Have you ever found the need to change the image you render on a web page based on the current preferred color scheme of your theme?",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/quick-tip-theme-aware-images.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lrr37qbdp22d",
    "location": "",
    "lastModified": 1750114559000
  },
  {
    "title": "Async Class Creation In JavaScript",
    "slug": "async-class-creation-in-javascript",
    "path": "/2025/june/async-class-creation-in-javascript",
    "date": 1748981098396,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "JavaScript",
      "TypeScript",
      "Tip"
    ],
    "description": "Have you ever wanted to create a class in JavaScript or TypeScript but also have the initialization be async? Here's a quick tip on a pattern that I've used in the past!",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/async-class-creation-in-javascript.png",
    "location": "",
    "lastModified": 1748981231000
  },
  {
    "title": "In Review - The Belroy Transit Workpack Pro v2",
    "slug": "belroy-transit-workpack-pro-v2",
    "path": "/2025/may/belroy-transit-workpack-pro-v2",
    "date": 1748517015808,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Product Review",
      "Backpack",
      "Gear",
      "Review"
    ],
    "description": "I semi-recently bought a Belroy Transit Workpack Pro v2 backpack, and after using it for about 9 months now I figured I'd write up some of my thoughts on it!",
    "month": "may",
    "year": 2025,
    "ogImage": "/og-images/belroy-transit-workpack-pro-v2.png",
    "location": "",
    "lastModified": 1748517256000
  },
  {
    "title": "Website Redesign v10",
    "slug": "website-redesign-v10",
    "path": "/2025/may/website-redesign-v10",
    "date": 1748209536031,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "Redesign"
    ],
    "description": "I recently launched a rewrite and redesign of this personal website, I figured I'd talk a bit about the changes and new features that I added along the way!",
    "month": "may",
    "year": 2025,
    "ogImage": "/og-images/website-redesign-v10.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lpzvssqktc23",
    "location": "",
    "lastModified": 1749594810000
  }
]