/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentMicroposts: Array<HydratedFrontmatter> = [
  {
    "title": "Link: How I build software quickly",
    "slug": "link-how-i-build-software-quickly",
    "path": "/2025/july/link-how-i-build-software-quickly",
    "date": 1752491842222,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Links"
    ],
    "month": "july",
    "year": 2025,
    "ogImage": "/og-images/link-how-i-build-software-quickly.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3ltwbyktpvk24",
    "location": "Boston, MA",
    "lastModified": 1752492295000
  },
  {
    "title": "Vacation (and streaks)",
    "slug": "vacation-and-streaks",
    "path": "/2025/july/vacation-and-streaks",
    "date": 1751898486318,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Travel"
    ],
    "month": "july",
    "year": 2025,
    "ogImage": "/og-images/vacation-and-streaks.png",
    "blueskyPostUri": "",
    "location": "Gold Beach, Vashon, WA.",
    "lastModified": 1751899155000
  },
  {
    "title": "Polish is Important",
    "slug": "polish-is-important",
    "path": "/2025/june/polish-is-important",
    "date": 1751028430594,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Software Development"
    ],
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/polish-is-important.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lslorqxyck26",
    "location": "Flying from BOS to PDX",
    "lastModified": 1751028932000
  },
  {
    "title": "<Blank> Driven Development",
    "slug": "blank-driven-development",
    "path": "/2025/june/blank-driven-development",
    "date": 1750690970088,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost"
    ],
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/blank-driven-development.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lsbunpzuvc2a",
    "location": "Boston, MA",
    "lastModified": 1750691628000
  },
  {
    "title": "All Documentation Should Be Dated",
    "slug": "all-documentation-should-be-dated",
    "path": "/2025/june/all-documentation-should-be-dated",
    "date": 1750422391010,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost"
    ],
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/all-documentation-should-be-dated.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3ls22jksebk2n",
    "location": "Boston, MA",
    "lastModified": 1750533014000
  }
]