/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentMicroposts: Array<HydratedFrontmatter> = [
  {
    "title": "All Documentation Should Be Dated",
    "slug": "all-documentation-should-be-dated",
    "path": "/2025/june/all-documentation-should-be-dated",
    "date": 1750422391010,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost"
    ],
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/all-documentation-should-be-dated.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3ls22jksebk2n",
    "location": "Boston",
    "lastModified": 1750423061000
  },
  {
    "title": "Adding Microposts",
    "slug": "adding-microposts",
    "path": "/2025/june/adding-microposts",
    "date": 1750379756763,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost"
    ],
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/adding-microposts.png",
    "blueskyPostUri": "",
    "location": "Taking the train back to Boston from Stamford",
    "lastModified": null
  }
]