/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let topPosts: Array<HydratedFrontmatter> = [
  {
    "title": "You're Building Software Wrong",
    "slug": "youre-building-software-wrong",
    "path": "/2025/february/youre-building-software-wrong",
    "date": 1739666520691,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "Software Development"
    ],
    "description": "Slicing software: why vertical is better than horizontal.",
    "month": "february",
    "year": 2025,
    "ogImage": "/og-images/youre-building-software-wrong.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3liazyp2ty225",
    "location": "",
    "lastModified": 1747695963000
  },
  {
    "title": "The AI Development Conundrum",
    "slug": "the-ai-development-conundrum",
    "path": "/2025/january/the-ai-development-conundrum",
    "date": 1738027723626,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "AI",
      "Development",
      "Opinion"
    ],
    "description": "Is it a good or a bad thing to offload writing code to AI agents and Large Language Models?",
    "month": "january",
    "year": 2025,
    "ogImage": "/og-images/the-ai-development-conundrum.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lgrcviqfyk2n",
    "location": "",
    "lastModified": 1748030308000
  },
  {
    "title": "Testing Software",
    "slug": "testing-software",
    "path": "/2018/december/testing-software",
    "date": 1543665600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Testing"
    ],
    "description": "",
    "month": "december",
    "year": 2018,
    "ogImage": "/og-images/testing-software.png",
    "location": "",
    "lastModified": 1747568207000
  },
  {
    "title": "Maintenance Costs",
    "slug": "maintenance-costs",
    "path": "/2019/may/maintenance-costs",
    "date": 1558267200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development"
    ],
    "description": "",
    "month": "may",
    "year": 2019,
    "ogImage": "/og-images/maintenance-costs.png",
    "location": "",
    "lastModified": 1747568207000
  },
  {
    "title": "Fractal Refactoring",
    "slug": "fractal-refactoring",
    "path": "/2023/june/fractal-refactoring",
    "date": 1686338680000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Rant",
      "Random"
    ],
    "description": "",
    "month": "june",
    "year": 2023,
    "ogImage": "/og-images/fractal-refactoring.png",
    "location": "",
    "lastModified": 1747568207000
  },
  {
    "title": "10x Engineers",
    "slug": "10x",
    "path": "/2023/june/10x",
    "date": 1685651637000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Development",
      "Rant"
    ],
    "description": "",
    "month": "june",
    "year": 2023,
    "ogImage": "/og-images/10x.png",
    "location": "",
    "lastModified": 1747568207000
  }
]