/// <reference types="bun" />
import { glob } from "tinyglobby";

let contents = `/* Autogenerated file */
/* do not edit */`;

let metadataPath = "./src/metadata.gen.ts";

let metadata = {};

let mdxDir = "./src/mdx";

let mdxFiles = await glob(`${mdxDir}/**/*.mdx`);
