/// <reference types="bun" />
import {
  type RawFrontmatter,
  collectMetadata,
  getMDXFiles,
} from "./collect-metadata";

let metadataPath = "./src/metadata.gen.ts";

export async function generateMetadata() {
  let contents = `/* Autogenerated file */
/* do not edit */`;

  let mdxFiles = await getMDXFiles();

  let metadata: Record<string, RawFrontmatter> =
    await collectMetadata(mdxFiles);

  contents += `
export let metadata = ${JSON.stringify(metadata, null, 2)};`;

  await Bun.write(metadataPath, contents);
  await Bun.$`bun run format`;
}
