/* Autogenerated file */
/* do not edit */
export const metadata = {
  "/2025/april/some-slug-here": {
    title: "Some Other Title",
    slug: "/2025/april/some-slug-here",
    date: 1745535484895,
    description: "Some short description here",
    tags: ["one", "two"],
  },
};
