/* Autogenerated file */
/* do not edit */

import type { HydratedFrontmatter } from "#/types";

export let metadata: Array<HydratedFrontmatter> = [
  {
    "title": "Roundup Notes in Obsidian with Dataview",
    "slug": "roundup-notes-in-obsidian-with-dataview",
    "path": "/2025/june/roundup-notes-in-obsidian-with-dataview",
    "date": 1750115552955,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Obsidian",
      "Tip",
      "Note Taking",
      "Development"
    ],
    "description": "A quick tip for creating roundup or summary notes based on other notes in Obsidian using the Dataview plugin!",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/roundup-notes-in-obsidian-with-dataview.png",
    "blueskyPostUri": "",
    "lastModified": null
  },
  {
    "title": "Quick Tip - Theme Aware Images",
    "slug": "quick-tip-theme-aware-images",
    "path": "/2025/june/quick-tip-theme-aware-images",
    "date": 1750114295541,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Tip",
      "Web Development",
      "Development"
    ],
    "description": "Have you ever found the need to change the image you render on a web page based on the current preferred color scheme of your theme?",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/quick-tip-theme-aware-images.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lrr37qbdp22d",
    "lastModified": 1750114559000
  },
  {
    "title": "Async Class Creation In JavaScript",
    "slug": "async-class-creation-in-javascript",
    "path": "/2025/june/async-class-creation-in-javascript",
    "date": 1748981098396,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "JavaScript",
      "TypeScript",
      "Tip"
    ],
    "description": "Have you ever wanted to create a class in JavaScript or TypeScript but also have the initialization be async? Here's a quick tip on a pattern that I've used in the past!",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/async-class-creation-in-javascript.png",
    "lastModified": 1748981231000
  },
  {
    "title": "In Review - The Belroy Transit Workpack Pro v2",
    "slug": "belroy-transit-workpack-pro-v2",
    "path": "/2025/may/belroy-transit-workpack-pro-v2",
    "date": 1748517015808,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Product Review",
      "Backpack",
      "Gear",
      "Review"
    ],
    "description": "I semi-recently bought a Belroy Transit Workpack Pro v2 backpack, and after using it for about 9 months now I figured I'd write up some of my thoughts on it!",
    "month": "may",
    "year": 2025,
    "ogImage": "/og-images/belroy-transit-workpack-pro-v2.png",
    "lastModified": 1748517256000
  },
  {
    "title": "Website Redesign v10",
    "slug": "website-redesign-v10",
    "path": "/2025/may/website-redesign-v10",
    "date": 1748209536031,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "Redesign"
    ],
    "description": "I recently launched a rewrite and redesign of this personal website, I figured I'd talk a bit about the changes and new features that I added along the way!",
    "month": "may",
    "year": 2025,
    "ogImage": "/og-images/website-redesign-v10.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lpzvssqktc23",
    "lastModified": 1749594810000
  },
  {
    "title": "Server Side Rendering Compatible CSS Theming",
    "slug": "server-side-rendering-compatible-css-theming",
    "path": "/2025/april/server-side-rendering-compatible-css-theming",
    "date": 1744749638305,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Theming",
      "CSS",
      "Next.js",
      "Waku",
      "React",
      "Tip"
    ],
    "description": "A quick tip to implementing CSS theming that's compatible with Server Side Rendered applications!",
    "month": "april",
    "year": 2025,
    "ogImage": "/og-images/server-side-rendering-compatible-css-theming.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lmuxdbcyzs27",
    "lastModified": 1749594810000
  },
  {
    "title": "Podcasting By Hand",
    "slug": "podcasting-by-hand",
    "path": "/2025/april/podcasting-by-hand",
    "date": 1744629340844,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Podcasting",
      "The Bikeshed Pod"
    ],
    "description": "A brief overview on how we launched The Bikeshed Podcast, including a deep dive in our recording and distribution workflows!",
    "month": "april",
    "year": 2025,
    "ogImage": "/og-images/podcasting-by-hand.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lmrgykvctc2s",
    "lastModified": 1749594810000
  },
  {
    "title": "Replacing Dropbox Capture with Raycast",
    "slug": "replacing-dropbox-capture-with-raycast",
    "path": "/2025/march/replacing-dropbox-capture-with-raycast",
    "date": 1741726568526,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Dropbox",
      "Raycast",
      "Tools",
      "Tip"
    ],
    "description": "Recently Dropbox announced that it was shutting down the Capture app/service, so I sought out an alternative that provided a similar user experience!",
    "month": "march",
    "year": 2025,
    "ogImage": "/og-images/replacing-dropbox-capture-with-raycast.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lk4xpoekkk2w",
    "lastModified": 1749594810000
  },
  {
    "title": "Quick Tip - Specific Local Module Declarations",
    "slug": "quick-tip-specific-local-module-definitions",
    "path": "/2025/february/quick-tip-specific-local-module-definitions",
    "date": 1740434087554,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "TypeScript",
      "Web Development",
      "Tip",
      "Development",
      "Node.js"
    ],
    "description": "A quick tip outlining how to provide specific TypeScript type definitions for a local module!",
    "month": "february",
    "year": 2025,
    "ogImage": "/og-images/quick-tip-specific-local-module-definitions.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lixdrwtbuk2k",
    "lastModified": 1749594810000
  },
  {
    "title": "On File-System Routing Conventions",
    "slug": "on-file-system-routing-conventions",
    "path": "/2025/february/on-file-system-routing-conventions",
    "date": 1740002305473,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Next.js",
      "Garbanzo",
      "Opinion"
    ],
    "description": "Some rough thoughts on building a file-system routing based web application",
    "month": "february",
    "year": 2025,
    "ogImage": "/og-images/on-file-system-routing-conventions.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3likrnc5f6k2x",
    "lastModified": 1749594810000
  },
  {
    "title": "You're Building Software Wrong",
    "slug": "youre-building-software-wrong",
    "path": "/2025/february/youre-building-software-wrong",
    "date": 1739666520691,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "Software Development"
    ],
    "description": "Slicing software: why vertical is better than horizontal.",
    "month": "february",
    "year": 2025,
    "ogImage": "/og-images/youre-building-software-wrong.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3liazyp2ty225",
    "lastModified": 1749594810000
  },
  {
    "title": "Cursor and Obsidian",
    "slug": "cursor-and-obsidian",
    "path": "/2025/february/cursor-and-obsidian",
    "date": 1739459465636,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "AI",
      "Obsidian",
      "Personal Knowledge Management"
    ],
    "description": "A quick look at combining Cursor with Obsidian to ask questions of your notes!",
    "month": "february",
    "year": 2025,
    "ogImage": "/og-images/cursor-and-obsidian.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3li2y4k6qyc22",
    "lastModified": 1749594810000
  },
  {
    "title": "Single File Web Apps",
    "slug": "single-file-web-apps",
    "path": "/2025/february/single-file-web-apps",
    "date": 1738603641815,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development"
    ],
    "description": "What if you could author an entire web application in a single file?",
    "month": "february",
    "year": 2025,
    "ogImage": "/og-images/single-file-web-apps.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lhc3lle2lk2p",
    "lastModified": 1749594810000
  },
  {
    "title": "The AI Development Conundrum",
    "slug": "the-ai-development-conundrum",
    "path": "/2025/january/the-ai-development-conundrum",
    "date": 1738027723626,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "AI",
      "Development",
      "Opinion"
    ],
    "description": "Is it a good or a bad thing to offload writing code to AI agents and Large Language Models?",
    "month": "january",
    "year": 2025,
    "ogImage": "/og-images/the-ai-development-conundrum.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lgrcviqfyk2n",
    "lastModified": 1749594810000
  },
  {
    "title": "Resetting Controlled Components in Forms",
    "slug": "resetting-controlled-components-in-forms",
    "path": "/2025/january/resetting-controlled-components-in-forms",
    "date": 1737211335595,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "React",
      "Web Development",
      "React Server Components"
    ],
    "description": "A quick way to handle resetting internal state in components when a parent form is submitted!",
    "month": "january",
    "year": 2025,
    "ogImage": "/og-images/resetting-controlled-components-in-forms.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lfzkm7ez2s2q",
    "lastModified": 1749594810000
  },
  {
    "title": "Thoughts on New Years Resolutions",
    "slug": "thoughts-on-new-years-resolutions",
    "path": "/2024/december/thoughts-on-new-years-resolutions",
    "date": 1735656777226,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Resolutions",
      "Goal",
      "Goals"
    ],
    "description": "You don't need to wait until January 1st to set yearly goals and resolutions for yourself!",
    "month": "december",
    "year": 2024,
    "ogImage": "/og-images/thoughts-on-new-years-resolutions.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lemi6tsles2n",
    "lastModified": 1749594810000
  },
  {
    "title": "Team Memes",
    "slug": "team-memes",
    "path": "/2024/december/team-memes",
    "date": 1734648754152,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Culture",
      "Team",
      "Random",
      "Organizations"
    ],
    "description": "A snippet of some shared terminology/concepts (memes) from my time on the Frontend Platform team at Wayfair!",
    "month": "december",
    "year": 2024,
    "ogImage": "/og-images/team-memes.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3ldoy5umql22v",
    "lastModified": 1749594810000
  },
  {
    "title": "A Quick Look at Import Maps",
    "slug": "a-quick-look-at-import-maps",
    "path": "/2024/december/a-quick-look-at-import-maps",
    "date": 1733527329325,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "Node.js"
    ],
    "description": "A brief look at Import Maps and package.json#imports to support isomorphic JavaScript applications!",
    "month": "december",
    "year": 2024,
    "ogImage": "/og-images/a-quick-look-at-import-maps.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lcodhjgeks2h",
    "lastModified": 1749594810000
  },
  {
    "title": "Recommended Tech Talks",
    "slug": "recommended-tech-talks",
    "path": "/2024/december/recommended-tech-talks",
    "date": 1733524033445,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "Recommendations",
      "Roundup",
      "Talks"
    ],
    "description": "A collection of tech talks that I regularly re-watch and also recommend to everyone!",
    "month": "december",
    "year": 2024,
    "ogImage": "/og-images/recommended-tech-talks.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lcoadxcvek2t",
    "lastModified": 1749594810000
  },
  {
    "title": "Request for a (minimal) RSC Framework",
    "slug": "request-for-minimal-rsc-framework",
    "path": "/2024/december/request-for-minimal-rsc-framework",
    "date": 1733086988056,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "React",
      "React Server Components",
      "Server Actions",
      "Forms"
    ],
    "description": "Some features and functionality that I'd like within a React Server Component compatible framework.",
    "month": "december",
    "year": 2024,
    "ogImage": "/og-images/request-for-minimal-rsc-framework.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lcbjezkjcc27",
    "lastModified": 1749594810000
  },
  {
    "title": "My Updated Obsidian Task Management",
    "slug": "my-updated-obsidian-task-management",
    "path": "/2024/november/my-updated-obsidian-task-management",
    "date": 1732584223913,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Note Taking",
      "Task Management",
      "Obsidian"
    ],
    "description": "A quick update on how I manage my tasks within Obsidian!",
    "month": "november",
    "year": 2024,
    "ogImage": "/og-images/my-updated-obsidian-task-management.png",
    "lastModified": 1748030308000
  },
  {
    "title": "Bluesky Tips and Tools",
    "slug": "bluesky-tips-and-tools",
    "path": "/2024/november/bluesky-tips-and-tools",
    "date": 1732560530372,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "Bluesky",
      "Tip"
    ],
    "description": "A (running) collection of Bluesky tips, tools, packages, and other misc things!",
    "month": "november",
    "year": 2024,
    "ogImage": "/og-images/bluesky-tips-and-tools.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lbsa7kpbf227",
    "lastModified": 1749594810000
  },
  {
    "title": "The Bookkeeping Pattern",
    "slug": "the-bookkeeping-pattern",
    "path": "/2024/october/the-bookkeeping-pattern",
    "date": 1729870852000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Next.js",
      "JavaScript",
      "Tip",
      "TypeScript",
      "React Server Components",
      "Server Actions",
      "Forms"
    ],
    "description": "A quick look at a small but powerful pattern I've been leveraging as of late!",
    "month": "october",
    "year": 2024,
    "ogImage": "/og-images/the-bookkeeping-pattern.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3l7ehzfgt5i2r",
    "lastModified": 1749594810000
  },
  {
    "title": "Building a Custom Ghostty Theme",
    "slug": "building-a-custom-ghostty-theme",
    "path": "/2024/october/building-a-custom-ghostty-theme",
    "date": 1729588952000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Ghostty"
    ],
    "description": "How to generate a custom Ghostty theme based on any iterm2 theme!",
    "month": "october",
    "year": 2024,
    "ogImage": "/og-images/building-a-custom-ghostty-theme.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3l746pzpkw32q",
    "lastModified": 1749594810000
  },
  {
    "title": "TSLite",
    "slug": "tslite",
    "path": "/2024/october/tslite",
    "date": 1729346029000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "TypeScript",
      "JavaScript"
    ],
    "description": "A proposal for a minimal variant of TypeScript!",
    "month": "october",
    "year": 2024,
    "ogImage": "/og-images/tslite.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3l6vh3yrdxk2j",
    "lastModified": 1749594810000
  },
  {
    "title": "Monorepo Tips and Tricks",
    "slug": "monorepo-tips-and-tricks",
    "path": "/2024/october/monorepo-tips-and-tricks",
    "date": 1728311888000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Monorepos"
    ],
    "description": "Sharing a few core recommendations when working within monorepos to make your life easier!",
    "month": "october",
    "year": 2024,
    "ogImage": "/og-images/monorepo-tips-and-tricks.png",
    "lastModified": 1748030010000
  },
  {
    "title": "Offload Complexity, Don't Offload Learning",
    "slug": "offload-complexity",
    "path": "/2024/october/offload-complexity",
    "date": 1727781677000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "AI",
      "Career",
      "Learning"
    ],
    "description": "A rough mental model for how you should be leveraging AI as a tool for your own growth",
    "month": "october",
    "year": 2024,
    "ogImage": "/og-images/offload-complexity.png",
    "lastModified": 1748030010000
  },
  {
    "title": "Next.js with Deno v2",
    "slug": "nextjs-with-deno-v2",
    "path": "/2024/september/nextjs-with-deno-v2",
    "date": 1726844212000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Deno",
      "Next.js"
    ],
    "description": "This is a quick post noting that Next.js should now work with Deno v2!",
    "month": "september",
    "year": 2024,
    "ogImage": "/og-images/nextjs-with-deno-v2.png",
    "lastModified": 1747568207000
  },
  {
    "title": "More Thoughts on Dogfooding",
    "slug": "more-thoughts-on-dogfooding",
    "path": "/2024/september/more-thoughts-on-dogfooding",
    "date": 1725877909000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Product"
    ],
    "description": "Even more thoughts on dogfooding!",
    "month": "september",
    "year": 2024,
    "ogImage": "/og-images/more-thoughts-on-dogfooding.png",
    "lastModified": 1748030010000
  },
  {
    "title": "Dogfooding",
    "slug": "dogfooding",
    "path": "/2024/august/dogfooding",
    "date": 1724254455000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Product"
    ],
    "description": "The secret to excellent product teams is using your own product, and often!",
    "month": "august",
    "year": 2024,
    "ogImage": "/og-images/dogfooding.png",
    "lastModified": 1748030308000
  },
  {
    "title": "Git Notes as a Tool for Thought",
    "slug": "git-notes-as-a-tool-for-thought",
    "path": "/2024/august/git-notes-as-a-tool-for-thought",
    "date": 1723282971000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Git",
      "Tools for Thought"
    ],
    "description": "(Ab)using Git as yet another tool for thought!",
    "month": "august",
    "year": 2024,
    "ogImage": "/og-images/git-notes-as-a-tool-for-thought.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Don't Break the Implicit Prop Contract",
    "slug": "dont-break-the-implicit-prop-contract",
    "path": "/2024/august/dont-break-the-implicit-prop-contract",
    "date": 1722879092000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Tip",
      "React"
    ],
    "description": "React components have a fundamental contract that is often unstated in their implementation, and you should know about it!",
    "month": "august",
    "year": 2024,
    "ogImage": "/og-images/dont-break-the-implicit-prop-contract.png",
    "lastModified": 1748030308000
  },
  {
    "title": "A Better useSSR Implementation",
    "slug": "a-better-useSSR-implementation",
    "path": "/2024/july/a-better-useSSR-implementation",
    "date": 1721737661000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Tip",
      "React",
      "Snippets"
    ],
    "description": "Replace that old useState and useEffect combo for a new and better option!",
    "month": "july",
    "year": 2024,
    "ogImage": "/og-images/a-better-useSSR-implementation.png",
    "lastModified": 1747568207000
  },
  {
    "title": "30",
    "slug": "30",
    "path": "/2024/july/30",
    "date": 1721455200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Birthday",
      "Goals",
      "Resolutions"
    ],
    "description": "A quick recap of my goals from the past year and a few goals looking forward as well.",
    "month": "july",
    "year": 2024,
    "ogImage": "/og-images/30.png",
    "lastModified": 1748030308000
  },
  {
    "title": "Simple Obsidian Task Management",
    "slug": "simple-obsidian-task-management",
    "path": "/2024/july/simple-obsidian-task-management",
    "date": 1721407719000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Notes",
      "Note Taking",
      "Obsidian",
      "Task Management"
    ],
    "description": "A brief overview of how I manage my tasks in Obsidian",
    "month": "july",
    "year": 2024,
    "ogImage": "/og-images/simple-obsidian-task-management.png",
    "lastModified": 1748030308000
  },
  {
    "title": "My Current Dev Setup",
    "slug": "my-current-dev-setup",
    "path": "/2024/july/my-current-dev-setup",
    "date": 1720467627000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "Tools"
    ],
    "description": "A quick look at the applications and tools that I (generally) use day to day for web development!",
    "month": "july",
    "year": 2024,
    "ogImage": "/og-images/my-current-dev-setup.png",
    "lastModified": 1748030010000
  },
  {
    "title": "Switching back to Obsidian",
    "slug": "switching-back-to-obsidian",
    "path": "/2024/july/switching-back-to-obsidian",
    "date": 1719845437000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Note Taking",
      "Obsidian",
      "Notion"
    ],
    "description": "Previously I wrote about switching from Obsidian to Notion, now almost exactly 2 years later, I've opted to give Obsidian another try as my go-to note taking software, here's why!",
    "month": "july",
    "year": 2024,
    "ogImage": "/og-images/switching-back-to-obsidian.png",
    "lastModified": 1748030010000
  },
  {
    "title": "There Is No Standard Markdown",
    "slug": "there-is-no-standard-markdown",
    "path": "/2024/july/there-is-no-standard-markdown",
    "date": 1719843881000,
    "status": "draft",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development"
    ],
    "description": "There are a variety of different markdown \"standards\" out there, and sometimes they're not all that consistent",
    "month": "july",
    "year": 2024,
    "ogImage": "/og-images/there-is-no-standard-markdown.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Abstract Your API",
    "slug": "abstract-your-api",
    "path": "/2024/june/abstract-your-api",
    "date": 1719737327000,
    "status": "draft",
    "type": "blog-post",
    "tags": [
      "APIs",
      "Web Development"
    ],
    "description": "Proposing a solution for sharing core \"business\" logic across services!",
    "month": "june",
    "year": 2024,
    "ogImage": "/og-images/abstract-your-api.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Tip: Request and Response Headers",
    "slug": "tip-request-and-response-headers",
    "path": "/2024/june/tip-request-and-response-headers",
    "date": 1718015824000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Tip",
      "Development",
      "Web Development"
    ],
    "description": "There's a common gotcha when creating Web Request and Response instances with Headers!",
    "month": "june",
    "year": 2024,
    "ogImage": "/og-images/tip-request-and-response-headers.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Using Feature Toggles to De-risk Refactors",
    "slug": "using-feature-toggles-to-de-risk-refactors",
    "path": "/2024/may/using-feature-toggles-to-de-risk-refactors",
    "date": 1716887064000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Refactors",
      "Development",
      "Next.js"
    ],
    "description": "Feature toggles are often underused by most software development teams, and yet offer so much value during not only feature development but also refactors",
    "month": "may",
    "year": 2024,
    "ogImage": "/og-images/using-feature-toggles-to-de-risk-refactors.png",
    "lastModified": 1748030010000
  },
  {
    "title": "Leaving Wayfair",
    "slug": "leaving-wayfair",
    "path": "/2024/may/leaving-wayfair",
    "date": 1715776784000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Career",
      "Looking Ahead",
      "Meta",
      "Thoughts",
      "Work"
    ],
    "description": "The other week was my last week at Wayfair, rounding out almost 8 years at the company. I wanted to reflect a bit on my time there!",
    "month": "may",
    "year": 2024,
    "ogImage": "/og-images/leaving-wayfair.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Hohoro",
    "slug": "hohoro",
    "path": "/2024/may/hohoro",
    "date": 1715616810000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "swc",
      "TypeScript",
      "Projects"
    ],
    "description": "A quick introduction to my new side project, hohoro. An incremental JS/TS library build tool!",
    "month": "may",
    "year": 2024,
    "ogImage": "/og-images/hohoro.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Funport: True Dynamic Imports in webpack",
    "slug": "funport",
    "path": "/2024/april/funport",
    "date": 1712952033000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "webpack",
      "Next.js"
    ],
    "description": "webpack, and tools built on it like Next.js, don't support true dynamic imports, but I found a way to trick the system!",
    "month": "april",
    "year": 2024,
    "ogImage": "/og-images/funport.png",
    "lastModified": 1747790496000
  },
  {
    "title": "My Current AI Stack",
    "slug": "my-current-ai-stack",
    "path": "/2024/april/my-current-ai-stack",
    "date": 1712335610000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "AI",
      "Development"
    ],
    "description": "I've been using a variety of AI tools as of late, I figured I'd document the ones I'm primarily using!",
    "month": "april",
    "year": 2024,
    "ogImage": "/og-images/my-current-ai-stack.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Configuring Cloudflare Domains with Vercel",
    "slug": "configuring-cloudflare-domains-with-vercel",
    "path": "/2024/april/configuring-cloudflare-domains-with-vercel",
    "date": 1712306350000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Guides",
      "Development",
      "Cloudflare",
      "Vercel"
    ],
    "description": "I've started to use Cloudflare to manage my domains for several side projects, have had to jump through the same hooks multiple times that I figured I should document them here!",
    "month": "april",
    "year": 2024,
    "ogImage": "/og-images/configuring-cloudflare-domains-with-vercel.png",
    "lastModified": 1747568207000
  },
  {
    "title": "React Error Boundaries: Revisited",
    "slug": "react-error-boundaries-revisited",
    "path": "/2024/march/react-error-boundaries-revisited",
    "date": 1711731624000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Guides",
      "Development",
      "React"
    ],
    "description": "Revising my previous blog post on React Error Boundaries and my preferred go-to implementation!",
    "month": "march",
    "year": 2024,
    "ogImage": "/og-images/react-error-boundaries-revisited.png",
    "lastModified": 1748030010000
  },
  {
    "title": "Exporting Custom Slack Emoji",
    "slug": "exporting-custom-slack-emoji",
    "path": "/2024/march/exporting-custom-slack-emoji",
    "date": 1711367133000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Slack",
      "Tip",
      "Guides"
    ],
    "description": "How to easily mass-export your custom slack emoji without API access!",
    "month": "march",
    "year": 2024,
    "ogImage": "/og-images/exporting-custom-slack-emoji.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Custom Favicon Recipes",
    "slug": "custom-favicon-recipes",
    "path": "/2024/march/custom-favicon-recipes",
    "date": 1711147710000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "Tip"
    ],
    "description": "Two neat tricks for enhancing your site's favicon!",
    "month": "march",
    "year": 2024,
    "ogImage": "/og-images/custom-favicon-recipes.png",
    "lastModified": 1750114422000
  },
  {
    "title": "Corporate Sponsored OSS",
    "slug": "corporate-sponsored-oss",
    "path": "/2024/march/corporate-sponsored-oss",
    "date": 1710083009000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "OSS"
    ],
    "description": "The various risks and pitfalls of open source software run by corporations.",
    "month": "march",
    "year": 2024,
    "ogImage": "/og-images/corporate-sponsored-oss.png",
    "lastModified": 1747568207000
  },
  {
    "title": "The Library-Docs Monorepo Template",
    "slug": "library-docs-monorepo-template",
    "path": "/2024/february/library-docs-monorepo-template",
    "date": 1708018253000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "Projects"
    ],
    "description": "A monorepo template for managing a library and documentation together.",
    "month": "february",
    "year": 2024,
    "ogImage": "/og-images/library-docs-monorepo-template.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Building Better Beacon",
    "slug": "building-better-beacon",
    "path": "/2024/january/building-better-beacon",
    "date": 1705388698000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "Projects"
    ],
    "description": "How we solved an almost show-stopping production bug, and how you can avoid it in your own projects.",
    "month": "january",
    "year": 2024,
    "ogImage": "/og-images/building-better-beacon.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Project Deep Dive: Tails",
    "slug": "project-deep-dive-tails",
    "path": "/2023/december/project-deep-dive-tails",
    "date": 1703934329000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Project Deep Dive",
      "Projects",
      "Web Development",
      "Cloudflare",
      "Next.js"
    ],
    "description": "A(nother) deep dive into one of my recent side projects; tails - a plain and simple cocktail recipe app.",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/project-deep-dive-tails.png",
    "lastModified": 1748030308000
  },
  {
    "title": "Churn Anxiety",
    "slug": "churn-anxiety",
    "path": "/2023/december/churn-anxiety",
    "date": 1703792233000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development"
    ],
    "description": "When did semver major changes become so scary?",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/churn-anxiety.png",
    "lastModified": 1748029406000
  },
  {
    "title": "Service Monitors and Observability",
    "slug": "service-monitors-and-observability",
    "path": "/2023/december/service-monitors-and-observability",
    "date": 1703690333000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "micropost",
      "Observability"
    ],
    "description": "Leveraging service monitors properly to improve service observability.",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/service-monitors-and-observability.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Type Safe process.env",
    "slug": "type-safe-process-env",
    "path": "/2023/december/type-safe-process-env",
    "date": 1703601283000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "TypeScript",
      "micropost",
      "Snippets"
    ],
    "description": "",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/type-safe-process-env.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Consistent Local Ports with Wrangler",
    "slug": "consistent-local-ports-with-wrangler",
    "path": "/2023/december/consistent-local-ports-with-wrangler",
    "date": 1703599291000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "micropost",
      "Cloudflare"
    ],
    "description": "",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/consistent-local-ports-with-wrangler.png",
    "lastModified": 1747568207000
  },
  {
    "title": "On Adopting CSS-in-JS",
    "slug": "on-adopting-css-in-js",
    "path": "/2023/december/on-adopting-css-in-js",
    "date": 1703050170000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "CSS-in-JS"
    ],
    "description": "A brief recap of how Wayfair changed it's CSS approach not once but twice in the span of 5 years!",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/on-adopting-css-in-js.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Being Unopinionated",
    "slug": "being-unopinionated",
    "path": "/2023/december/being-unopinionated",
    "date": 1702885418000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "micropost"
    ],
    "description": "It's fine for a library to express some opinions about how it should be adopted and how the overall workflow/application in which it is adopted should function. However, it's false advertising to say that it is unopinionated.",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/being-unopinionated.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Stop Snacking",
    "slug": "stop-snacking",
    "path": "/2023/december/stop-snacking",
    "date": 1702628745000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "micropost",
      "Development"
    ],
    "description": "No I don't mean those Milano cookies you keep taking from the office snack wall either (although you should probably stop snacking on those as often as well).",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/stop-snacking.png",
    "lastModified": 1747568207000
  },
  {
    "title": "No Process is Invisible Process",
    "slug": "no-process-is-invisible-process",
    "path": "/2023/december/no-process-is-invisible-process",
    "date": 1702495052000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "micropost",
      "Teams"
    ],
    "description": "Low/no process workflow wasn't actually no process, it was only an \"invisible\" process. An implicit contract with everyone on the team to do that async workflow on their own time.",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/no-process-is-invisible-process.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Fixing Zed's language server",
    "slug": "fixing-zeds-language-server",
    "path": "/2023/december/fixing-zeds-language-server",
    "date": 1702024329000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Tip",
      "Zed"
    ],
    "description": "Zed language server quick tip; fixing Zed's language server",
    "month": "december",
    "year": 2023,
    "ogImage": "/og-images/fixing-zeds-language-server.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Project Deep Dive: Microfibre",
    "slug": "project-deep-dive-microfibre",
    "path": "/2023/november/project-deep-dive-microfibre",
    "date": 1701112500000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Project Deep Dive",
      "Projects",
      "Web Development",
      "Go",
      "Cloudflare",
      "Next.js"
    ],
    "description": "A deep dive into one of my recent side projects; microfibre - a minimal text posting application",
    "month": "november",
    "year": 2023,
    "ogImage": "/og-images/project-deep-dive-microfibre.png",
    "lastModified": 1748030308000
  },
  {
    "title": "Pair Programming",
    "slug": "pair-programming",
    "path": "/2023/november/pair-programming",
    "date": 1701013501000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development"
    ],
    "description": "Pair programming can be good sometimes - but not all the time",
    "month": "november",
    "year": 2023,
    "ogImage": "/og-images/pair-programming.png",
    "lastModified": 1748029406000
  },
  {
    "title": "AI Driven Development",
    "slug": "ai-driven-development",
    "path": "/2023/november/ai-driven-development",
    "date": 1700405709000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "ChatGPT",
      "AI"
    ],
    "description": "",
    "month": "november",
    "year": 2023,
    "ogImage": "/og-images/ai-driven-development.png",
    "lastModified": 1748029406000
  },
  {
    "title": "Teams and Caterpillar Tracks",
    "slug": "teams-and-caterpillar-tracks",
    "path": "/2023/november/teams-and-caterpillar-tracks",
    "date": 1699375122000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Teams"
    ],
    "description": "",
    "month": "november",
    "year": 2023,
    "ogImage": "/og-images/teams-and-caterpillar-tracks.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Go To Git Utils",
    "slug": "go-to-git-utils",
    "path": "/2023/october/go-to-git-utils",
    "date": 1696936441000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "Git"
    ],
    "description": "",
    "month": "october",
    "year": 2023,
    "ogImage": "/og-images/go-to-git-utils.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Jabs and Fluff: On CTO Office Hours",
    "slug": "on-cto-office-hours",
    "path": "/2023/september/on-cto-office-hours",
    "date": 1695639494000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Hot Take",
      "micropost"
    ],
    "description": "",
    "month": "september",
    "year": 2023,
    "ogImage": "/og-images/on-cto-office-hours.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Using Marquee with React and TypeScript",
    "slug": "using-marquee-with-react-and-typescript",
    "path": "/2023/september/using-marquee-with-react-and-typescript",
    "date": 1695468762000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "React",
      "TypeScript"
    ],
    "description": "",
    "month": "september",
    "year": 2023,
    "ogImage": "/og-images/using-marquee-with-react-and-typescript.png",
    "lastModified": 1748029406000
  },
  {
    "title": "Finding React Artifacts",
    "slug": "finding-react-artifacts",
    "path": "/2023/september/finding-react-artifacts",
    "date": 1695073727000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Development",
      "micropost"
    ],
    "description": "",
    "month": "september",
    "year": 2023,
    "ogImage": "/og-images/finding-react-artifacts.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Learning Go",
    "slug": "learning-go",
    "path": "/2023/september/learning-go",
    "date": 1693561835000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "Go",
      "Learning"
    ],
    "description": "",
    "month": "september",
    "year": 2023,
    "ogImage": "/og-images/learning-go.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Speedbumps",
    "slug": "speedbumps",
    "path": "/2023/august/speedbumps",
    "date": 1692380853000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Organizations",
      "Teams"
    ],
    "description": "",
    "month": "august",
    "year": 2023,
    "ogImage": "/og-images/speedbumps.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Idea: Distributable Web Apps",
    "slug": "distributable-web-apps",
    "path": "/2023/july/distributable-web-apps",
    "date": 1690608299000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Ideas"
    ],
    "description": "",
    "month": "july",
    "year": 2023,
    "ogImage": "/og-images/distributable-web-apps.png",
    "lastModified": 1747568207000
  },
  {
    "title": "29",
    "slug": "29",
    "path": "/2023/july/29",
    "date": 1689791818000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Birthday",
      "Goals",
      "Resolutions"
    ],
    "description": "",
    "month": "july",
    "year": 2023,
    "ogImage": "/og-images/29.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Principles for Automated Testing",
    "slug": "principles-for-automated-testing",
    "path": "/2023/july/principles-for-automated-testing",
    "date": 1688721133000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development"
    ],
    "description": "",
    "month": "july",
    "year": 2023,
    "ogImage": "/og-images/principles-for-automated-testing.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Deno",
    "slug": "deno",
    "path": "/2023/july/deno",
    "date": 1688673261000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "micropost",
      "Deno"
    ],
    "description": "",
    "month": "july",
    "year": 2023,
    "ogImage": "/og-images/deno.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Fractal Refactoring",
    "slug": "fractal-refactoring",
    "path": "/2023/june/fractal-refactoring",
    "date": 1686338680000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Rant",
      "Random"
    ],
    "description": "",
    "month": "june",
    "year": 2023,
    "ogImage": "/og-images/fractal-refactoring.png",
    "lastModified": 1747568207000
  },
  {
    "title": "10x Engineers",
    "slug": "10x",
    "path": "/2023/june/10x",
    "date": 1685651637000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Development",
      "Rant"
    ],
    "description": "",
    "month": "june",
    "year": 2023,
    "ogImage": "/og-images/10x.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Avoid Distractions",
    "slug": "avoid-distractions",
    "path": "/2023/april/avoid-distractions",
    "date": 1681561251000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Advice",
      "Rant"
    ],
    "description": "",
    "month": "april",
    "year": 2023,
    "ogImage": "/og-images/avoid-distractions.png",
    "lastModified": 1748029406000
  },
  {
    "title": "My Thoughts on Tailwind",
    "slug": "thoughts-on-tailwind",
    "path": "/2023/april/thoughts-on-tailwind",
    "date": 1681159895000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Tailwind",
      "CSS"
    ],
    "description": "",
    "month": "april",
    "year": 2023,
    "ogImage": "/og-images/thoughts-on-tailwind.png",
    "lastModified": 1748029406000
  },
  {
    "title": "Setting up Next.js with Tailwind",
    "slug": "nextjs-with-tailwind",
    "path": "/2023/april/nextjs-with-tailwind",
    "date": 1680771054000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Next.js",
      "Tailwind"
    ],
    "description": "",
    "month": "april",
    "year": 2023,
    "ogImage": "/og-images/nextjs-with-tailwind.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Write it down",
    "slug": "write-it-down",
    "path": "/2023/march/write-it-down",
    "date": 1680253201000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thoughts",
      "Communication"
    ],
    "description": "",
    "month": "march",
    "year": 2023,
    "ogImage": "/og-images/write-it-down.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Setting up Shiki on Next.js",
    "slug": "shiki-on-next-js",
    "path": "/2023/march/shiki-on-next-js",
    "date": 1679850459000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "Next.js"
    ],
    "description": "",
    "month": "march",
    "year": 2023,
    "ogImage": "/og-images/shiki-on-next-js.png",
    "lastModified": 1748029406000
  },
  {
    "title": "Dollar: Devlog 2",
    "slug": "dollar-devlog-2",
    "path": "/2023/march/dollar-devlog-2",
    "date": 1679827620000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Dollar",
      "Projects"
    ],
    "description": "",
    "month": "march",
    "year": 2023,
    "ogImage": "/og-images/dollar-devlog-2.png",
    "lastModified": 1748030308000
  },
  {
    "title": "Navigating Monorepos with Ease",
    "slug": "navigating-monorepos-with-ease",
    "path": "/2023/january/navigating-monorepos-with-ease",
    "date": 1675097870000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development",
      "Monorepos"
    ],
    "description": "",
    "month": "january",
    "year": 2023,
    "ogImage": "/og-images/navigating-monorepos-with-ease.png",
    "lastModified": 1748030308000
  },
  {
    "title": "Dollar: Devlog 1",
    "slug": "dollar-devlog-1",
    "path": "/2023/january/dollar-devlog-1",
    "date": 1674917826000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Dollar",
      "Projects"
    ],
    "description": "",
    "month": "january",
    "year": 2023,
    "ogImage": "/og-images/dollar-devlog-1.png",
    "lastModified": 1748029406000
  },
  {
    "title": "My Updated Next.js Setup",
    "slug": "updated-opinionated-nextjs-setup",
    "path": "/2022/december/updated-opinionated-nextjs-setup",
    "date": 1672037995000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Next.js"
    ],
    "description": "",
    "month": "december",
    "year": 2022,
    "ogImage": "/og-images/updated-opinionated-nextjs-setup.png",
    "lastModified": 1748028894000
  },
  {
    "title": "Yarn Berry Gitignore Settings",
    "slug": "yarn-berry-gitignore",
    "path": "/2022/july/yarn-berry-gitignore",
    "date": 1658389656000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Yarn"
    ],
    "description": "",
    "month": "july",
    "year": 2022,
    "ogImage": "/og-images/yarn-berry-gitignore.png",
    "lastModified": 1748028894000
  },
  {
    "title": "On Note Taking",
    "slug": "on-note-taking",
    "path": "/2022/june/on-note-taking",
    "date": 1656407184000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Tools for Thought",
      "Note Taking"
    ],
    "description": "",
    "month": "june",
    "year": 2022,
    "ogImage": "/og-images/on-note-taking.png",
    "lastModified": 1748028894000
  },
  {
    "title": "On Writing Tests",
    "slug": "on-writing-tests",
    "path": "/2022/june/on-writing-tests",
    "date": 1656275961000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Testing"
    ],
    "description": "",
    "month": "june",
    "year": 2022,
    "ogImage": "/og-images/on-writing-tests.png",
    "lastModified": 1748028894000
  },
  {
    "title": "Switching back to Notion",
    "slug": "switching-back-to-notion",
    "path": "/2022/may/switching-back-to-notion",
    "date": 1653846676000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Note Taking",
      "Obsidian",
      "Notion"
    ],
    "description": "",
    "month": "may",
    "year": 2022,
    "ogImage": "/og-images/switching-back-to-notion.png",
    "lastModified": 1748030308000
  },
  {
    "title": "Moving to PNPM",
    "slug": "moving-to-pnpm",
    "path": "/2022/may/moving-to-pnpm",
    "date": 1653138076000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development"
    ],
    "description": "",
    "month": "may",
    "year": 2022,
    "ogImage": "/og-images/moving-to-pnpm.png",
    "lastModified": 1748028894000
  },
  {
    "title": "Upgrade Guides",
    "slug": "upgrade-guides",
    "path": "/2022/may/upgrade-guides",
    "date": 1652783129000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development"
    ],
    "description": "",
    "month": "may",
    "year": 2022,
    "ogImage": "/og-images/upgrade-guides.png",
    "lastModified": 1748028894000
  },
  {
    "title": "My Opinionated Next.js Setup",
    "slug": "my-opinionated-nextjs-setup",
    "path": "/2022/january/my-opinionated-nextjs-setup",
    "date": 1643541028000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Next.js"
    ],
    "description": "",
    "month": "january",
    "year": 2022,
    "ogImage": "/og-images/my-opinionated-nextjs-setup.png",
    "lastModified": 1748028894000
  },
  {
    "title": "My Two Favorite React Tricks",
    "slug": "my-two-favorite-react-tricks",
    "path": "/2022/january/my-two-favorite-react-tricks",
    "date": 1643228713000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "React",
      "Development"
    ],
    "description": "",
    "month": "january",
    "year": 2022,
    "ogImage": "/og-images/my-two-favorite-react-tricks.png",
    "lastModified": 1748030308000
  },
  {
    "title": "Switching to iPhone",
    "slug": "switching-to-iphone",
    "path": "/2022/january/switching-to-iphone",
    "date": 1642257821000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Review",
      "Android",
      "iOS",
      "iPhone"
    ],
    "description": "",
    "month": "january",
    "year": 2022,
    "ogImage": "/og-images/switching-to-iphone.png",
    "lastModified": 1748028894000
  },
  {
    "title": "Year in Music",
    "slug": "2021-in-music",
    "path": "/2021/december/2021-in-music",
    "date": 1637998249000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Recap"
    ],
    "description": "",
    "month": "december",
    "year": 2021,
    "ogImage": "/og-images/2021-in-music.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Pair Programming (stub)",
    "slug": "pair-programming-stub",
    "path": "/2021/november/pair-programming-stub",
    "date": 1637404850000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "stub"
    ],
    "description": "",
    "month": "november",
    "year": 2021,
    "ogImage": "/og-images/pair-programming-stub.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Fast Feedback Systems",
    "slug": "fast-feedback-systems",
    "path": "/2021/november/fast-feedback-systems",
    "date": 1637404297000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "micropost"
    ],
    "description": "",
    "month": "november",
    "year": 2021,
    "ogImage": "/og-images/fast-feedback-systems.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Video Games",
    "slug": "video-games",
    "path": "/2021/november/video-games",
    "date": 1637401671000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "micropost"
    ],
    "description": "",
    "month": "november",
    "year": 2021,
    "ogImage": "/og-images/video-games.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Delete it",
    "slug": "delete-it",
    "path": "/2021/october/delete-it",
    "date": 1634379511000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "micropost"
    ],
    "description": "",
    "month": "october",
    "year": 2021,
    "ogImage": "/og-images/delete-it.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Linear Tools Enforce Linear Thinking",
    "slug": "linear-tools",
    "path": "/2021/september/linear-tools",
    "date": 1630772502000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Rant",
      "Tools for Thought"
    ],
    "description": "",
    "month": "september",
    "year": 2021,
    "ogImage": "/og-images/linear-tools.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Mac Setup Guide",
    "slug": "mac-setup-guide",
    "path": "/2021/september/mac-setup-guide",
    "date": 1630761615000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Guides"
    ],
    "description": "",
    "month": "september",
    "year": 2021,
    "ogImage": "/og-images/mac-setup-guide.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Build Your Developer Toolbox",
    "slug": "build-your-developer-toolbox",
    "path": "/2021/august/build-your-developer-toolbox",
    "date": 1630088843000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development"
    ],
    "description": "",
    "month": "august",
    "year": 2021,
    "ogImage": "/og-images/build-your-developer-toolbox.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Start Fresh",
    "slug": "start-fresh",
    "path": "/2021/august/start-fresh",
    "date": 1630086205000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Productivity"
    ],
    "description": "",
    "month": "august",
    "year": 2021,
    "ogImage": "/og-images/start-fresh.png",
    "lastModified": 1748028740000
  },
  {
    "title": "On Written Communication",
    "slug": "on-written-communication",
    "path": "/2021/august/on-written-communication",
    "date": 1629832211000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Collaboration",
      "Communication",
      "Writing"
    ],
    "description": "",
    "month": "august",
    "year": 2021,
    "ogImage": "/og-images/on-written-communication.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Updating Forked Repos",
    "slug": "updating-forked-repos",
    "path": "/2021/august/updating-forked-repos",
    "date": 1629644473000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Git",
      "Tip"
    ],
    "description": "",
    "month": "august",
    "year": 2021,
    "ogImage": "/og-images/updating-forked-repos.png",
    "lastModified": 1748028740000
  },
  {
    "title": "React Testing Library: Checkboxes and events",
    "slug": "rtl-checkbox-events",
    "path": "/2021/august/rtl-checkbox-events",
    "date": 1628615660000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "React Testing Library",
      "React"
    ],
    "description": "",
    "month": "august",
    "year": 2021,
    "ogImage": "/og-images/rtl-checkbox-events.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Roll your own Obsidian sync",
    "slug": "obsidian-sync",
    "path": "/2021/august/obsidian-sync",
    "date": 1628596800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Obsidian",
      "Dropbox"
    ],
    "description": "",
    "month": "august",
    "year": 2021,
    "ogImage": "/og-images/obsidian-sync.png",
    "lastModified": 1748028740000
  },
  {
    "title": "The Squeeze",
    "slug": "the-squeeze",
    "path": "/2021/june/the-squeeze",
    "date": 1624881600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thoughts",
      "Work"
    ],
    "description": "",
    "month": "june",
    "year": 2021,
    "ogImage": "/og-images/the-squeeze.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Learning",
    "slug": "learning",
    "path": "/2021/june/learning",
    "date": 1623585600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thoughts"
    ],
    "description": "",
    "month": "june",
    "year": 2021,
    "ogImage": "/og-images/learning.png",
    "lastModified": 1747568207000
  },
  {
    "title": "On Code Review",
    "slug": "on-code-review",
    "path": "/2021/march/on-code-review",
    "date": 1615809600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development Practices",
      "Code Review"
    ],
    "description": "",
    "month": "march",
    "year": 2021,
    "ogImage": "/og-images/on-code-review.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Array Chunking",
    "slug": "array-chunking",
    "path": "/2021/march/array-chunking",
    "date": 1615118400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "JavaScript",
      "Development"
    ],
    "description": "",
    "month": "march",
    "year": 2021,
    "ogImage": "/og-images/array-chunking.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Fast",
    "slug": "fast",
    "path": "/2021/march/fast",
    "date": 1614600000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development Practices"
    ],
    "description": "",
    "month": "march",
    "year": 2021,
    "ogImage": "/og-images/fast.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Writing Node Scripts",
    "slug": "writing-node-scripts",
    "path": "/2021/march/writing-node-scripts",
    "date": 1614600000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Node"
    ],
    "description": "",
    "month": "march",
    "year": 2021,
    "ogImage": "/og-images/writing-node-scripts.png",
    "lastModified": 1748028740000
  },
  {
    "title": "useConsole",
    "slug": "useConsole",
    "path": "/2021/february/useConsole",
    "date": 1613304000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Snippets",
      "JavaScript",
      "React",
      "Development"
    ],
    "description": "",
    "month": "february",
    "year": 2021,
    "ogImage": "/og-images/useConsole.png",
    "lastModified": 1748028740000
  },
  {
    "title": "yw",
    "slug": "yw",
    "path": "/2021/february/yw",
    "date": 1612785600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Snippets",
      "Yarn",
      "Monorepos",
      "Development"
    ],
    "description": "",
    "month": "february",
    "year": 2021,
    "ogImage": "/og-images/yw.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Hack Sprint",
    "slug": "hack-sprint",
    "path": "/2021/january/hack-sprint",
    "date": 1611057600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Hacking"
    ],
    "description": "",
    "month": "january",
    "year": 2021,
    "ogImage": "/og-images/hack-sprint.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Simple Props",
    "slug": "simple-props",
    "path": "/2021/january/simple-props",
    "date": 1610971200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Side Projects"
    ],
    "description": "",
    "month": "january",
    "year": 2021,
    "ogImage": "/og-images/simple-props.png",
    "lastModified": 1748028740000
  },
  {
    "title": "Computed Design Tokens",
    "slug": "computed-theme",
    "path": "/2021/january/computed-theme",
    "date": 1610193600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Design Systems",
      "Theme"
    ],
    "description": "",
    "month": "january",
    "year": 2021,
    "ogImage": "/og-images/computed-theme.png",
    "lastModified": 1748028740000
  },
  {
    "title": "2021: Resolutions",
    "slug": "2021",
    "path": "/2021/january/2021",
    "date": 1609502400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Resolutions"
    ],
    "description": "",
    "month": "january",
    "year": 2021,
    "ogImage": "/og-images/2021.png",
    "lastModified": 1748030308000
  },
  {
    "title": "2020: Year in Review",
    "slug": "2020",
    "path": "/2020/december/2020",
    "date": 1609416000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Recap"
    ],
    "description": "",
    "month": "december",
    "year": 2020,
    "ogImage": "/og-images/2020.png",
    "lastModified": 1748026839000
  },
  {
    "title": "Building a Web Sandbox: Part 1",
    "slug": "sandbox-part-1",
    "path": "/2020/december/sandbox-part-1",
    "date": 1608552000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Side Projects"
    ],
    "description": "",
    "month": "december",
    "year": 2020,
    "ogImage": "/og-images/sandbox-part-1.png",
    "lastModified": 1748026839000
  },
  {
    "title": "Literate (web) Programming",
    "slug": "literate-programming",
    "path": "/2020/december/literate-programming",
    "date": 1608379200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Ideas"
    ],
    "description": "",
    "month": "december",
    "year": 2020,
    "ogImage": "/og-images/literate-programming.png",
    "lastModified": 1748026839000
  },
  {
    "title": "NextJS Analytics with Airtable",
    "slug": "nextjs-analytics-with-airtable",
    "path": "/2020/december/nextjs-analytics-with-airtable",
    "date": 1607860800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Side Projects"
    ],
    "description": "",
    "month": "december",
    "year": 2020,
    "ogImage": "/og-images/nextjs-analytics-with-airtable.png",
    "lastModified": 1748026839000
  },
  {
    "title": "Pair Code Reviews",
    "slug": "pair-code-reviews",
    "path": "/2020/december/pair-code-reviews",
    "date": 1606910400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Collaboration",
      "Code Review"
    ],
    "description": "",
    "month": "december",
    "year": 2020,
    "ogImage": "/og-images/pair-code-reviews.png",
    "lastModified": 1748026839000
  },
  {
    "title": "Enhancing Slack",
    "slug": "enhancing-slack",
    "path": "/2020/july/enhancing-slack",
    "date": 1594209600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Slack",
      "Product Development"
    ],
    "description": "",
    "month": "july",
    "year": 2020,
    "ogImage": "/og-images/enhancing-slack.png",
    "lastModified": 1748028065000
  },
  {
    "title": "A Note on Consistency",
    "slug": "a-note-on-consistency",
    "path": "/2020/may/a-note-on-consistency",
    "date": 1590926400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Collaboration",
      "Teams"
    ],
    "description": "",
    "month": "may",
    "year": 2020,
    "ogImage": "/og-images/a-note-on-consistency.png",
    "lastModified": 1747568207000
  },
  {
    "title": "The Rabbit Hole",
    "slug": "the-rabbit-hole",
    "path": "/2020/april/the-rabbit-hole",
    "date": 1586001600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Side Projects"
    ],
    "description": "",
    "month": "april",
    "year": 2020,
    "ogImage": "/og-images/the-rabbit-hole.png",
    "lastModified": 1747568207000
  },
  {
    "title": "A Note On Meetings",
    "slug": "a-note-on-meetings",
    "path": "/2020/april/a-note-on-meetings",
    "date": 1585915200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Meetings",
      "Note"
    ],
    "description": "",
    "month": "april",
    "year": 2020,
    "ogImage": "/og-images/a-note-on-meetings.png",
    "lastModified": 1747568207000
  },
  {
    "title": "A Note On Anti-Patterns",
    "slug": "a-note-on-anti-patterns",
    "path": "/2020/april/a-note-on-anti-patterns",
    "date": 1585828800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Note"
    ],
    "description": "",
    "month": "april",
    "year": 2020,
    "ogImage": "/og-images/a-note-on-anti-patterns.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Stateful Providers",
    "slug": "stateful-providers",
    "path": "/2020/march/stateful-providers",
    "date": 1585396800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "React",
      "Development Practices"
    ],
    "description": "",
    "month": "march",
    "year": 2020,
    "ogImage": "/og-images/stateful-providers.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Draft Pull Requests",
    "slug": "draft-pull-requests",
    "path": "/2020/march/draft-pull-requests",
    "date": 1584964800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Collaboration",
      "Code Review"
    ],
    "description": "",
    "month": "march",
    "year": 2020,
    "ogImage": "/og-images/draft-pull-requests.png",
    "lastModified": 1747568207000
  },
  {
    "title": "February 20, 2020",
    "slug": "back-bay-fens",
    "path": "/2020/february/back-bay-fens",
    "date": 1582200000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Photos",
      "Back Bay"
    ],
    "description": "",
    "month": "february",
    "year": 2020,
    "ogImage": "/og-images/back-bay-fens.png",
    "lastModified": 1748027978000
  },
  {
    "title": "Summer 2019 - Bend Oregon",
    "slug": "bend",
    "path": "/2019/july/bend",
    "date": 1564228800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Travel",
      "Bend"
    ],
    "description": "",
    "month": "july",
    "year": 2019,
    "ogImage": "/og-images/bend.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Theme First UI Development",
    "slug": "theme-first-ui-development",
    "path": "/2019/july/theme-first-ui-development",
    "date": 1563451200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "React",
      "Design Tokens",
      "Design Systems"
    ],
    "description": "",
    "month": "july",
    "year": 2019,
    "ogImage": "/og-images/theme-first-ui-development.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Deploying Automatically using GitHub Actions",
    "slug": "deploying-with-github-actions",
    "path": "/2019/june/deploying-with-github-actions",
    "date": 1559476800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development"
    ],
    "description": "",
    "month": "june",
    "year": 2019,
    "ogImage": "/og-images/deploying-with-github-actions.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Simpler and Smaller",
    "slug": "simpler-and-smaller",
    "path": "/2019/june/simpler-and-smaller",
    "date": 1559390400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development"
    ],
    "description": "",
    "month": "june",
    "year": 2019,
    "ogImage": "/og-images/simpler-and-smaller.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Maintenance Costs",
    "slug": "maintenance-costs",
    "path": "/2019/may/maintenance-costs",
    "date": 1558267200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development"
    ],
    "description": "",
    "month": "may",
    "year": 2019,
    "ogImage": "/og-images/maintenance-costs.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Snapshot Testing",
    "slug": "snapshot-testing",
    "path": "/2019/march/snapshot-testing",
    "date": 1551441600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Testing"
    ],
    "description": "",
    "month": "march",
    "year": 2019,
    "ogImage": "/og-images/snapshot-testing.png",
    "lastModified": 1747568207000
  },
  {
    "title": "useReducer, don't useState",
    "slug": "why-you-should-useReducer",
    "path": "/2019/february/why-you-should-useReducer",
    "date": 1549800000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "React"
    ],
    "description": "",
    "month": "february",
    "year": 2019,
    "ogImage": "/og-images/why-you-should-useReducer.png",
    "lastModified": 1748026165000
  },
  {
    "title": "Hooks Tips Ep. 2 - Migrating Instance Variables",
    "slug": "hooks-tips-instance-variables",
    "path": "/2019/february/hooks-tips-instance-variables",
    "date": 1549368000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "React"
    ],
    "description": "",
    "month": "february",
    "year": 2019,
    "ogImage": "/og-images/hooks-tips-instance-variables.png",
    "lastModified": 1748026165000
  },
  {
    "title": "Hooks Tips Ep. 1 - The Dependency Array",
    "slug": "hooks-tips-dependency-array",
    "path": "/2019/february/hooks-tips-dependency-array",
    "date": 1549108800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "React"
    ],
    "description": "",
    "month": "february",
    "year": 2019,
    "ogImage": "/og-images/hooks-tips-dependency-array.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Building a Live Editor",
    "slug": "building-a-live-editor",
    "path": "/2019/february/building-a-live-editor",
    "date": 1549022400001,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Side Projects"
    ],
    "description": "",
    "month": "february",
    "year": 2019,
    "ogImage": "/og-images/building-a-live-editor.png",
    "lastModified": 1748026165000
  },
  {
    "title": "Start Small, Accept Change",
    "slug": "start-small",
    "path": "/2019/february/start-small",
    "date": 1549022400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Side Projects"
    ],
    "description": "",
    "month": "february",
    "year": 2019,
    "ogImage": "/og-images/start-small.png",
    "lastModified": 1748026165000
  },
  {
    "title": "React Error Boundaries",
    "slug": "react-error-boundaries",
    "path": "/2019/january/react-error-boundaries",
    "date": 1548936000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "React"
    ],
    "description": "",
    "month": "january",
    "year": 2019,
    "ogImage": "/og-images/react-error-boundaries.png",
    "lastModified": 1748026165000
  },
  {
    "title": "Starting Fresh",
    "slug": "starting-fresh",
    "path": "/2018/december/starting-fresh",
    "date": 1544011200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thoughts",
      "Redesign"
    ],
    "description": "",
    "month": "december",
    "year": 2018,
    "ogImage": "/og-images/starting-fresh.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Testing Software",
    "slug": "testing-software",
    "path": "/2018/december/testing-software",
    "date": 1543665600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Testing"
    ],
    "description": "",
    "month": "december",
    "year": 2018,
    "ogImage": "/og-images/testing-software.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Suspense Plus GraphQL",
    "slug": "suspense-plus-graphql",
    "path": "/2018/november/suspense-plus-graphql",
    "date": 1541948640000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "React",
      "GraphQL",
      "Suspense",
      "Web Development"
    ],
    "description": "A few thoughts on using Suspense with GraphQL to optimize application data loading",
    "month": "november",
    "year": 2018,
    "ogImage": "/og-images/suspense-plus-graphql.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Missing Detail",
    "slug": "missing-detail",
    "path": "/2018/november/missing-detail",
    "date": 1541356200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Article"
    ],
    "description": "A few thoughts on the article \"Reality has a surprising amount of detail\"",
    "month": "november",
    "year": 2018,
    "ogImage": "/og-images/missing-detail.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Matt's Log - October",
    "slug": "matts-log-october",
    "path": "/2018/october/matts-log-october",
    "date": 1538514660000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Log"
    ],
    "description": "A quick log of what I have been up to in October",
    "month": "october",
    "year": 2018,
    "ogImage": "/og-images/matts-log-october.png",
    "lastModified": 1747568207000
  },
  {
    "title": "You've Launched, Now What?",
    "slug": "youve-launched-now-what",
    "path": "/2018/september/youve-launched-now-what",
    "date": 1537715160000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "Launch"
    ],
    "description": "A few thoughts on what to do after you launch a new project",
    "month": "september",
    "year": 2018,
    "ogImage": "/og-images/youve-launched-now-what.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Summer 2018 Trip",
    "slug": "summer-2018-trip",
    "path": "/2018/july/summer-2018-trip",
    "date": 1532179380000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Travel",
      "Photos"
    ],
    "description": "A few photos from my summer trip!",
    "month": "july",
    "year": 2018,
    "ogImage": "/og-images/summer-2018-trip.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Taking a Break",
    "slug": "taking-a-break",
    "path": "/2018/july/taking-a-break",
    "date": 1530695220000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Burnout",
      "Web Development",
      "Development"
    ],
    "description": "A few quick thoughts on burn out and taking a break",
    "month": "july",
    "year": 2018,
    "ogImage": "/og-images/taking-a-break.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Managing Complex UI Component State",
    "slug": "complex-ui-components",
    "path": "/2018/may/complex-ui-components",
    "date": 1527508800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "React",
      "Web Development",
      "Components"
    ],
    "description": "A few thoughts on managing complex UI component state within React",
    "month": "may",
    "year": 2018,
    "ogImage": "/og-images/complex-ui-components.png",
    "lastModified": 1748025572000
  },
  {
    "title": "Understanding React 16.3 Updates",
    "slug": "understanding-react-16-3-updates",
    "path": "/2018/april/understanding-react-16-3-updates",
    "date": 1523210040000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "React",
      "JavaScript",
      "Web Development"
    ],
    "description": "A quick overview of the new lifecycle methods introduced in React 16.3",
    "month": "april",
    "year": 2018,
    "ogImage": "/og-images/understanding-react-16-3-updates.png",
    "lastModified": 1747568207000
  },
  {
    "title": "2018",
    "slug": "2018",
    "path": "/2018/january/2018",
    "date": 1516104000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Recap",
      "Looking Ahead"
    ],
    "description": "A recap and update on some of the projects I am working on at the start of 2018",
    "month": "january",
    "year": 2018,
    "ogImage": "/og-images/2018.png",
    "lastModified": 1747568207000
  },
  {
    "title": "CSS in JS",
    "slug": "css-in-js",
    "path": "/2017/april/css-in-js",
    "date": 1491048000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "CSS",
      "JavaScript",
      "Web Development"
    ],
    "description": "A few thoughts and patterns for using styled-jsx or other CSS-in-JS solutions",
    "month": "april",
    "year": 2017,
    "ogImage": "/og-images/css-in-js.png",
    "lastModified": 1748025572000
  },
  {
    "title": "Redesign v6",
    "slug": "redesign-v6",
    "path": "/2017/march/redesign-v6",
    "date": 1489579200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Redesign",
      "Thoughts",
      "Next.js",
      "Web Development"
    ],
    "description": "A few thoughts on the redesign of my personal site, adopting Next.js and deploying via Now",
    "month": "march",
    "year": 2017,
    "ogImage": "/og-images/redesign-v6.png",
    "lastModified": 1747568207000
  },
  {
    "title": "JavaScript Weirdness",
    "slug": "javascript-weirdness",
    "path": "/2017/march/javascript-weirdness",
    "date": 1489233600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "JavaScript",
      "Web Development"
    ],
    "description": "A few weird things about JavaScript",
    "month": "march",
    "year": 2017,
    "ogImage": "/og-images/javascript-weirdness.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Calendar",
    "slug": "calendar",
    "path": "/2017/march/calendar",
    "date": 1489147200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Calendar",
      "Web Development"
    ],
    "description": "Building a calendar web application",
    "month": "march",
    "year": 2017,
    "ogImage": "/og-images/calendar.png",
    "lastModified": 1748025572000
  },
  {
    "title": "Rebuilding Mustache",
    "slug": "rebuilding-mustache",
    "path": "/2017/march/rebuilding-mustache",
    "date": 1488369600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "Web Development"
    ],
    "description": "",
    "month": "march",
    "year": 2017,
    "ogImage": "/og-images/rebuilding-mustache.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Push vs Pull AI",
    "slug": "push-vs-pull-ai",
    "path": "/2017/january/push-vs-pull-ai",
    "date": 1483272000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Technology",
      "AI"
    ],
    "description": "",
    "month": "january",
    "year": 2017,
    "ogImage": "/og-images/push-vs-pull-ai.png",
    "lastModified": 1747691492000
  },
  {
    "title": "Links",
    "slug": "links",
    "path": "/2016/november/links",
    "date": 1479556800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Roundup",
      "Collection"
    ],
    "description": "",
    "month": "november",
    "year": 2016,
    "ogImage": "/og-images/links.png",
    "lastModified": 1747568207000
  },
  {
    "title": "The Great CSS Debate",
    "slug": "css-debate",
    "path": "/2016/october/css-debate",
    "date": 1475928000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development",
      "CSS"
    ],
    "description": "",
    "month": "october",
    "year": 2016,
    "ogImage": "/og-images/css-debate.png",
    "lastModified": 1747691974000
  },
  {
    "title": "October 4th",
    "slug": "october-4th",
    "path": "/2016/october/october-4th",
    "date": 1475582400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Technology",
      "Google"
    ],
    "description": "",
    "month": "october",
    "year": 2016,
    "ogImage": "/og-images/october-4th.png",
    "lastModified": 1747692981000
  },
  {
    "title": "My New Website",
    "slug": "my-new-website",
    "path": "/2016/august/my-new-website",
    "date": 1472385600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Redesign",
      "Thoughts"
    ],
    "description": "",
    "month": "august",
    "year": 2016,
    "ogImage": "/og-images/my-new-website.png",
    "lastModified": 1747691492000
  },
  {
    "title": "Pull Quotes",
    "slug": "pull-quotes",
    "path": "/2016/august/pull-quotes",
    "date": 1472040000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web",
      "Thoughts"
    ],
    "description": "",
    "month": "august",
    "year": 2016,
    "ogImage": "/og-images/pull-quotes.png",
    "lastModified": 1748025126000
  },
  {
    "title": "Redesign v5",
    "slug": "redesign-v5",
    "path": "/2016/august/redesign-v5",
    "date": 1472040000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thoughts",
      "Redesign"
    ],
    "description": "",
    "month": "august",
    "year": 2016,
    "ogImage": "/og-images/redesign-v5.png",
    "lastModified": 1748025126000
  },
  {
    "title": "Attribute Selectors",
    "slug": "attribute-selectors",
    "path": "/2016/august/attribute-selectors",
    "date": 1471780800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "CSS",
      "Development"
    ],
    "description": "",
    "month": "august",
    "year": 2016,
    "ogImage": "/og-images/attribute-selectors.png",
    "lastModified": 1747568207000
  },
  {
    "title": "August",
    "slug": "august",
    "path": "/2016/august/august",
    "date": 1471694400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Recap"
    ],
    "description": "",
    "month": "august",
    "year": 2016,
    "ogImage": "/og-images/august.png",
    "lastModified": 1748025126000
  },
  {
    "title": "Redesign",
    "slug": "redesign",
    "path": "/2016/april/redesign",
    "date": 1459771200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thoughts",
      "Redesign"
    ],
    "description": "",
    "month": "april",
    "year": 2016,
    "ogImage": "/og-images/redesign.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Afraid",
    "slug": "afraid",
    "path": "/2016/january/afraid",
    "date": 1453464000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Meta"
    ],
    "description": "",
    "month": "january",
    "year": 2016,
    "ogImage": "/og-images/afraid.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Clientside",
    "slug": "clientside",
    "path": "/2016/january/clientside",
    "date": 1453204800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Development"
    ],
    "description": "",
    "month": "january",
    "year": 2016,
    "ogImage": "/og-images/clientside.png",
    "lastModified": 1748025126000
  },
  {
    "title": "10,000 Characters",
    "slug": "10000-characters",
    "path": "/2016/january/10000-characters",
    "date": 1452081600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Twitter",
      "Thoughts"
    ],
    "description": "",
    "month": "january",
    "year": 2016,
    "ogImage": "/og-images/10000-characters.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Building in 2016",
    "slug": "building-in-2016",
    "path": "/2016/january/building-in-2016",
    "date": 1451822400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Projects"
    ],
    "description": "",
    "month": "january",
    "year": 2016,
    "ogImage": "/og-images/building-in-2016.png",
    "lastModified": 1747568207000
  },
  {
    "title": "DJI vs GoPro",
    "slug": "dji-vs-gopro",
    "path": "/2016/january/dji-vs-gopro",
    "date": 1451649600001,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Technology",
      "Competition"
    ],
    "description": "",
    "month": "january",
    "year": 2016,
    "ogImage": "/og-images/dji-vs-gopro.png",
    "lastModified": 1748025126000
  },
  {
    "title": "My First Project of 2016",
    "slug": "my-first-project-of-2016",
    "path": "/2016/january/my-first-project-of-2016",
    "date": 1451649600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Projects"
    ],
    "description": "",
    "month": "january",
    "year": 2016,
    "ogImage": "/og-images/my-first-project-of-2016.png",
    "lastModified": 1748025126000
  },
  {
    "title": "2015",
    "slug": "2015",
    "path": "/2015/december/2015",
    "date": 1451563200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Recap"
    ],
    "description": "",
    "month": "december",
    "year": 2015,
    "ogImage": "/og-images/2015.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Looking Ahead: 2016",
    "slug": "2016",
    "path": "/2015/december/2016",
    "date": 1451563200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Looking Ahead"
    ],
    "description": "",
    "month": "december",
    "year": 2015,
    "ogImage": "/og-images/2016.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Blogging vs Working",
    "slug": "blogging-vs-working",
    "path": "/2015/december/blogging-vs-working",
    "date": 1450180800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thoughts"
    ],
    "description": "",
    "month": "december",
    "year": 2015,
    "ogImage": "/og-images/blogging-vs-working.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Powerpoint",
    "slug": "powerpoint",
    "path": "/2015/december/powerpoint",
    "date": 1449057600000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Startups",
      "Ideas"
    ],
    "description": "",
    "month": "december",
    "year": 2015,
    "ogImage": "/og-images/powerpoint.png",
    "lastModified": 1747568207000
  },
  {
    "title": "The Social Max",
    "slug": "the-social-max",
    "path": "/2015/december/the-social-max",
    "date": 1448971200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Social Media"
    ],
    "description": "",
    "month": "december",
    "year": 2015,
    "ogImage": "/og-images/the-social-max.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Thanksgiving",
    "slug": "thanksgiving",
    "path": "/2015/november/thanksgiving",
    "date": 1448366400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thanks"
    ],
    "description": "",
    "month": "november",
    "year": 2015,
    "ogImage": "/og-images/thanksgiving.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Family Time",
    "slug": "family-time",
    "path": "/2015/november/family-time",
    "date": 1448020800000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Family"
    ],
    "description": "",
    "month": "november",
    "year": 2015,
    "ogImage": "/og-images/family-time.png",
    "lastModified": 1747568207000
  },
  {
    "title": "Weekend Projects",
    "slug": "weekend-projects",
    "path": "/2015/november/weekend-projects",
    "date": 1446638400000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Side Projects"
    ],
    "description": "",
    "month": "november",
    "year": 2015,
    "ogImage": "/og-images/weekend-projects.png",
    "lastModified": 1747568207000
  },
  {
    "title": "The Message is in the Medium",
    "slug": "message",
    "path": "/2015/november/message",
    "date": 1446552000000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Meta",
      "Communication"
    ],
    "description": "",
    "month": "november",
    "year": 2015,
    "ogImage": "/og-images/message.png",
    "lastModified": 1747568207000
  },
  {
    "title": "A New Look",
    "slug": "a-new-look",
    "path": "/2015/november/a-new-look",
    "date": 1446379200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thoughts",
      "Redesign"
    ],
    "description": "",
    "month": "november",
    "year": 2015,
    "ogImage": "/og-images/a-new-look.png",
    "lastModified": 1747568207000
  },
  {
    "title": "A New Resume",
    "slug": "a-new-resume",
    "path": "/2015/november/a-new-resume",
    "date": 1446379200000,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Career",
      "Side Projects"
    ],
    "description": "",
    "month": "november",
    "year": 2015,
    "ogImage": "/og-images/a-new-resume.png",
    "lastModified": 1747568207000
  }
];