/* Autogenerated file */
/* do not edit */
export let metadata = {
  "/2025/april/some-slug-here": {
    title: "Some Other Title",
    slug: "/2025/april/some-slug-here",
    date: 1745535484895,
    description: "An edited short description here",
    tags: ["one", "two"],
  },
  "/2025/may/another-one": {
    title: "Another One",
    slug: "/2025/may/another-one",
    date: 1745535484895,
    description: "An edited short description here",
    tags: ["one", "two"],
  },
};
